<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="2" skipped="2">
  <reporter-output>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Sorry your TC is failed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Test case p is running]]>
    </line>
    <line>
      <![CDATA[Congarts your TC is passed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Your TC is Skipped, please check]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Test case a is running]]>
    </line>
    <line>
      <![CDATA[Congarts your TC is passed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Sorry your TC is failed]]>
    </line>
    <line>
      <![CDATA[Your TC is started]]>
    </line>
    <line>
      <![CDATA[Your TC is Skipped, please check]]>
    </line>
  </reporter-output>
  <suite started-at="2022-04-01T20:12:14 GMT-05:00" name="Suite" finished-at="2022-04-01T20:12:14 GMT-05:00" duration-ms="224">
    <groups>
    </groups>
    <test started-at="2022-04-01T20:12:14 GMT-05:00" name="Test" finished-at="2022-04-01T20:12:14 GMT-05:00" duration-ms="224">
      <class name="listner.Testing1">
        <test-method signature="q()[pri:0, instance:listner.Testing1@618425b5]" started-at="2022-04-01T20:12:14 GMT-05:00" name="q" finished-at="2022-04-01T20:12:14 GMT-05:00" duration-ms="23" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listner.Testing1.q(Testing1.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[Sorry your TC is failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- q -->
        <test-method signature="p()[pri:0, instance:listner.Testing1@618425b5]" started-at="2022-04-01T20:12:14 GMT-05:00" name="p" finished-at="2022-04-01T20:12:14 GMT-05:00" duration-ms="3" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[Test case p is running]]>
            </line>
            <line>
              <![CDATA[Congarts your TC is passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- p -->
        <test-method signature="r()[pri:0, instance:listner.Testing1@618425b5]" started-at="2022-04-01T20:12:14 GMT-05:00" name="r" finished-at="2022-04-01T20:12:14 GMT-05:00" depends-on-methods="listner.Testing1.q" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testing1.r()[pri:0, instance:listner.Testing1@618425b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testing1.r()[pri:0, instance:listner.Testing1@618425b5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[Your TC is Skipped, please check]]>
            </line>
          </reporter-output>
        </test-method> <!-- r -->
      </class> <!-- listner.Testing1 -->
      <class name="listner.Testing">
        <test-method signature="a()[pri:0, instance:listner.Testing@434a63ab]" started-at="2022-04-01T20:12:14 GMT-05:00" name="a" finished-at="2022-04-01T20:12:14 GMT-05:00" duration-ms="6" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[Test case a is running]]>
            </line>
            <line>
              <![CDATA[Congarts your TC is passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- a -->
        <test-method signature="b()[pri:0, instance:listner.Testing@434a63ab]" started-at="2022-04-01T20:12:14 GMT-05:00" name="b" finished-at="2022-04-01T20:12:14 GMT-05:00" duration-ms="8" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listner.Testing.b(Testing.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Your TC is started]]>
            </line>
            <line>
              <![CDATA[Sorry your TC is failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- b -->
        <test-method signature="c()[pri:0, instance:listner.Testing@434a63ab]" started-at="2022-04-01T20:12:14 GMT-05:00" name="c" finished-at="2022-04-01T20:12:14 GMT-05:00" depends-on-methods="listner.Testing.b" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testing.c()[pri:0, instance:listner.Testing@434a63ab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testing.c()[pri:0, instance:listner.Testing@434a63ab] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[Your TC is Skipped, please check]]>
            </line>
          </reporter-output>
        </test-method> <!-- c -->
      </class> <!-- listner.Testing -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
